spring:
  application:
    name: foodsave
  datasource:
    url: jdbc:postgresql://localhost:5432/foodsave
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  avatar:
    upload-dir: uploads/avatars
    max-size: 5242880 # 5MB in bytes
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true

logging:
  level:
    root: INFO
    foodsave.com.foodsave: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 